### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-module-carrier-update#1]
In 2.4.3-p3 version 1.1 of this module no longer offers to create DHL postage for orders with shipping_method="m2eproshipping_m2eproshipping" despite "M2Epro Shipping" being selected in "Stores → Configuration → Sales → Post & DHL Shipping → DHL Parcel Germany → Checkout Presentation".

**Comment by mam08ixo** [comment]
On 2.4.5, I configured _Table Rate_ as _Additional Shipping Method_ and after checkout, the order could be fulfilled with DHL Paket in the admin panel as expected. From my point of view, the module still works on recent Magento versions. You will have to find out what exactly changed in your environment that made it "stop working".

**Comment by ngolatka** [comment]
Closed due to inactivity.

**Comment by simonrl** [comment]
Hi @YiffyToys I am having a similar issue, also with M2ePro and with international orders only, while German orders still work. Did you find anything back then which could help me?

Thanks upfront!

**Comment by YiffyToys** [comment]
I still have my old Magento extension that was needed before this feature existed.
It adds a menu item to change the shipping method as a poor workaround.

Being only on Amazon.de after Brexit (Amazon.co.uk) I don't get many international Amazon orders.
(In fact, they are a headache for O.S.S. book keeping.)
I'll keep and eye out if this is indeed when it happens. If so, I can debug further.

**Update:** We had an Aamzon order from a non-EU country and the issue did not happen. Will wait for an intra-EU export order it doesn't look good for this guess.
