### ISSUE TITLE
support for PHP 8.2 and dhl/module-carrier-paket 3.x

### ISSUE THREAD

**Issue by YiffyToys** [netresearch/dhl-module-carrier-update#2]
Seems to no longer be compatible with Magento 2.4.7

**Comment by powli** [comment]
Might very well be. As stated in the [README](https://github.com/netresearch/dhl-module-carrier-update/blob/master/README.md#support) we will not perform maintenance for this extension.

Users are free to provide PRs with the necessary changes.

**Comment by YiffyToys** [comment]
Already in progress.
Still worth documenting  open issues with a ticket. Even if it's just to have a ticket number to reference in commit messages.
Will take a while to verify it functions properly.

The original mass-action from https://github.com/netresearch/dhl-shipping-m2/issues/11 still works fine as a workaround.

**Comment by Sebastian80** [comment]
Hi, 

we releases [Version 1.2.0](https://github.com/netresearch/dhl-module-carrier-update/releases/tag/1.2.0),
which is now compatible with magento 2.4.7.
